---
extends:
- airbnb
- plugin:flowtype/recommended
- plugin:react/recommended
- prettier
plugins:
- flowtype
- react
settings:
  import/parser: babel-eslint
env:
  browser: true
  jest: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  no-console:
    - 0
  no-underscore-dangle:
    - 0
