// flow-typed signature: 887cda6deab88b97717560ae62d94a9e
// flow-typed version: <<STUB>>/babel-plugin-react-html-attrs_v^2.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-html-attrs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-html-attrs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-html-attrs/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-html-attrs/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-html-attrs/lib/index'>;
}
