# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install dependencies
      - run: 
          name: Installing dependencies
          command: yarn install

      # save to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      # run tests!
      - run:
          name: Linting
          command: yarn lint
        
      - run:
          name: Flowing
          command: yarn flow

      - run: 
          name: Running tests
          command: yarn test --maxWorkers 2

      # build for measuring bundle size
      - run: 
          name: Building
          command: yarn build

      # upload stats file
      - store_artifacts:
          path: dist/index.js
